# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: snapdragon-kernel
summary: snapdragon linux kernel
description: The Ubuntu kernel package as a snap

grade: stable
build-base: core22
confinement: strict
type: kernel

architectures:
  - build-on: [arm64, amd64]
    build-for: arm64

parts:
  kernel:
    plugin: kernel
    kernel-kdefconfig: [ "snappy_defconfig" ]
    kernel-image-target: Image.gz
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    prime:
      - -Image*
      - -kernel.img

  initrd:
    after:
      - firmware
      - kernel
    plugin: initrd
    initrd-stage-firmware: true
    initrd-firmware:
      - renesas_usb_fw.mem
    initrd-modules:
      - i2c-qcom-cci
      - i2c-qcom-geni
      - libarc4
      - mdt-loader
      - phy-qcom-qusb2
      - qcom_glink_smem
      - qmi-helpers
      - rtc-pm8xxx
      - slim_qcom_ngd_ctrl
      - slimbus
      - wcd934x
      - xhci-pci
      - xhci-pci-renesas
    prime:
      - -initrd*

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
      - wireless-regdb
    override-pull: |
      for f in firmware-atheros firmware-qcom-dragonboard410c firmware-qcom-dragonboard820c firmware-qcom-dragonboard845c firmware-qcom-media firmware-qcom-soc
      do
        version="$(curl -s http://obs.linaro.org/linaro-overlay-sid/sid/Packages.gz | zcat | grep "${f}" |grep "Filename" | tail -1 | awk '{ print $2}' | cut -c3-)"
        echo "current_version=${version}"
        curl -O http://obs.linaro.org/linaro-overlay-sid/sid/${version}
      done
    override-build: |
      find ${SNAPCRAFT_PART_SRC} -name "*.deb" -exec dpkg -x {} ${SNAPCRAFT_PART_INSTALL} \;
    organize:
      lib/firmware: firmware
    prime:
      - firmware

build-packages:
  - bison
  - device-tree-compiler
  - dpkg-dev
  - flex
  - gcc
  - libfdt-dev
  - libssl-dev
  - mkbootimg
  - pahole
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - rt5-clients
  - wget
