# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: snapdragon-kernel
summary: snapdragon linux kernel
description: The Ubuntu kernel package as a snap

grade: stable
build-base: core22
confinement: strict
type: kernel

architectures:
  - build-on: [arm64, amd64]
    build-for: arm64

parts:
  kernel:
    plugin: kernel
    kernel-kdefconfig: [ "snappy_defconfig" ]
    kernel-image-target: Image.gz
    build-environment:
      - PATH: "/usr/lib/ccache:${PATH}"
    prime:
      - -Image*
      - -kernel.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware
    prime:
      - -usr
      - -lib
    build-packages:
      - cpio
      - libssl-dev

build-packages:
  - bison
  - device-tree-compiler
  - dpkg-dev
  - flex
  - gcc
  - libfdt-dev
  - libssl-dev
  - mkbootimg
  - pahole
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - rt5-clients
  - wget
